### ISSUE TITLE
[Safari] Deleting whole text breaks undo

### ISSUE THREAD

**Issue by maxbarnas** [ckeditor/ckeditor5-undo#42]
1. Go to: [http://localhost:1030/build/modules/amd/tests/undo/manual/undo](http://localhost:1030/build/modules/amd/tests/undo/manual/undo).
2. Select whole text and delete it.
3. Press undo, then press Redo twice.

In console you will see errors following errors and the editor will be stuck:
```
[Log] TypeError: undefined is not an object (evaluating 'this.parent.getChild') (client.js, line 319)
[Log] TypeError: undefined is not an object (evaluating 'item.batch') (client.js, line 319)
```

**Comment by Reinmar** [comment]
Not a problem any more. TBH, I don't know why it wasn't working, but at the same time the test was a bit incorrect, because it was leading to stripping out the heading from the content (the feature wasn't loaded). After I fixed that everything work. The bug must be still there, but let's wait until we can reproduce it in a normal way.
